### ISSUE TITLE
テキストエリアに日本語が入力できない問題

### ISSUE THREAD

**Issue by nokok** [nokok/TwitDuke#70]
ツイートのテキストエリアに日本語が入力できない。
英字及び記号は入力可能。
また、実行中のTwitDukeでのみ発生しており、JavaFX SceneBuilder上の
プレビューでは入力可能である。

**Comment by nokok** [comment]
コピペで入力可能だが直接日本語を入力できない。

**Comment by nokok** [comment]
いつも発生するというわけではない模様。
二重で入力されるときもある

**Comment by satanabe1** [comment]
main.fxmlの79行目
`onInputMethodTextChanged="#tweetTextAreaOnTextChanged"`
を消すと、問題なさそう。

**Comment by nokok** [comment]
いつの間にか直ってたのでCloseします
